app = "ivaoth-bot"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[deploy]
  min_machines_running = 1

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "ivaodata"
  destination = "/data"